name: backdrop-downstreamer-2
recipe: backdrop

services:
  database:
    type: backdrop-mysql:8.0

# do not remove this
plugins:
  "@lando/backdrop": ../..
  "@lando/mysql": ../../node_modules/@lando/mysql
